### ISSUE TITLE
How to Compile msi fan control

### ISSUE THREAD

**Issue by rahulhingve** [raven112/MSI_GF63_EFI_OpenCore#1]
Can you give me instructions on compiling  MSIFanControl for my MacOS Sonoma Hackintosh? I have an MSI-GF63-Thin-9SCXR with an i7-9750H with single fan. Thank you.

**Comment by raven112** [comment]
I've just used Xcode for that. just install it, then clone repo for fan control from GitHub https://github.com/lgs3137/MSIFanControl
(or you can just download it from GitHub instead of cloning)
and compile it.

as far as I remember, I have had no problems with it (but I've used Ventura for that)
